package ru.mozevil.controller.vm;

public class KeyCode {

    private KeyCode() {}
//
    public static final int PRESS_A = 0x1E;
    public static final int PRESS_B = 0x30;
    public static final int PRESS_C = 0x2E;
    public static final int PRESS_D = 0x20;
    public static final int PRESS_E = 0x12;
    public static final int PRESS_F = 0x21;
    public static final int PRESS_G = 0x22;
    public static final int PRESS_H = 0x23;
    public static final int PRESS_I = 0x17;
    public static final int PRESS_J = 0x24;
    public static final int PRESS_K = 0x25;
    public static final int PRESS_L = 0x26;
    public static final int PRESS_M = 0x32;
    public static final int PRESS_N = 0x31;
    public static final int PRESS_O = 0x18;
    public static final int PRESS_P = 0x19;
    public static final int PRESS_Q = 0x10;
    public static final int PRESS_R = 0x13;
    public static final int PRESS_S = 0x1F;
    public static final int PRESS_T = 0x14;
    public static final int PRESS_U = 0x16;
    public static final int PRESS_V = 0x2F;
    public static final int PRESS_W = 0x11;
    public static final int PRESS_X = 0x2D;
    public static final int PRESS_Y = 0x15;
    public static final int PRESS_Z = 0x2C;
    public static final int PRESS_0 = 0x0B;
    public static final int PRESS_1 = 0x02;
    public static final int PRESS_2 = 0x03;
    public static final int PRESS_3 = 0x04;
    public static final int PRESS_4 = 0x05;
    public static final int PRESS_5 = 0x06;
    public static final int PRESS_6 = 0x07;
    public static final int PRESS_7 = 0x08;
    public static final int PRESS_8 = 0x09;
    public static final int PRESS_9 = 0x0A;
    public static final int PRESS_TILDA = 0x29;
    public static final int PRESS_MINUS = 0x0C; // -
    public static final int PRESS_EQUALS = 0x0D; // =
    public static final int PRESS_BACKSLASH = 0x2B; // \
    public static final int PRESS_LEFT_SQUARE_BRACKET = 0x1A; // [
    public static final int PRESS_RIGHT_SQUARE_BRACKET = 0x1B; // ]
    public static final int PRESS_SEMICOLON = 0x27; // ;
    public static final int PRESS_SINGLE_QUOTE = 0x28; // '
    public static final int PRESS_COMMA = 0x33; // ,
    public static final int PRESS_DOT = 0x34; // .
    public static final int PRESS_SLASH = 0x35; // /
    public static final int PRESS_BACKSPACE = 0x0E;
    public static final int PRESS_SPACE = 0x39;
    public static final int PRESS_TAB = 0x0F;
    public static final int PRESS_CAPS_LOCK = 0x3A;
    public static final int PRESS_SHIFT = 0x2A; // left
    public static final int PRESS_CTRL = 0x1D; // left
    public static final int PRESS_ALT = 0x38; // left
    public static final int PRESS_ENTER = 0x1C;
    public static final int PRESS_ESC = 0x01;
    public static final int PRESS_F1 = 0x3B;
    public static final int PRESS_F2 = 0x3C;
    public static final int PRESS_F3 = 0x3D;
    public static final int PRESS_F4 = 0x3E;
    public static final int PRESS_F5 = 0x3F;
    public static final int PRESS_F6 = 0x40;
    public static final int PRESS_F7 = 0x41;
    public static final int PRESS_F8 = 0x42;
    public static final int PRESS_F9 = 0x43;
    public static final int PRESS_F10 = 0x44;
    public static final int PRESS_F11 = 0x57;
    public static final int PRESS_F12 = 0x58;

    public static final int RELEASE_F12 = 0xD8;
    public static final int RELEASE_F11 = 0xD7;
    public static final int RELEASE_F10 = 0xC4;
    public static final int RELEASE_F9 = 0xC3;
    public static final int RELEASE_F8 = 0xC2;
    public static final int RELEASE_F7 = 0xC1;
    public static final int RELEASE_F6 = 0xC0;
    public static final int RELEASE_F5 = 0xBF;
    public static final int RELEASE_F4 = 0xBE;
    public static final int RELEASE_F3 = 0xBD;
    public static final int RELEASE_F2 = 0xBC;
    public static final int RELEASE_F1 = 0xBB;
    public static final int RELEASE_ESC = 0x81;
    public static final int RELEASE_ENTER = 0x9C;
    public static final int RELEASE_ALT = 0xB8; // left
    public static final int RELEASE_CTRL = 0x9D; // left
    public static final int RELEASE_SHIFT = 0xAA; // left
    public static final int RELEASE_CAPS_LOCK = 0xBA;
    public static final int RELEASE_TAB = 0x8F;
    public static final int RELEASE_SPACE = 0xB9;
    public static final int RELEASE_BACKSPACE = 0x8E;
    public static final int RELEASE_SLASH = 0xB5; // /
    public static final int RELEASE_DOT = 0xB4; // .
    public static final int RELEASE_COMMA = 0xB3; // ,
    public static final int RELEASE_SINGLE_QUOTE = 0xA8; // '
    public static final int RELEASE_SEMICOLON = 0xA7; // ;
    public static final int RELEASE_RIGHT_SQUARE_BRACKET = 0x9B; // ]
    public static final int RELEASE_LEFT_SQUARE_BRACKET = 0x9A; // [
    public static final int RELEASE_BACKSLASH = 0xAB; // \
    public static final int RELEASE_EQUALS = 0x82; // =
    public static final int RELEASE_MINUS = 0x8C; // -
    public static final int RELEASE_TILDA = 0x89;
    public static final int RELEASE_9 = 0x8A;
    public static final int RELEASE_8 = 0x89;
    public static final int RELEASE_7 = 0x88;
    public static final int RELEASE_6 = 0x87;
    public static final int RELEASE_5 = 0x86;
    public static final int RELEASE_4 = 0x85;
    public static final int RELEASE_3 = 0x84;
    public static final int RELEASE_2 = 0x83;
    public static final int RELEASE_1 = 0x82;
    public static final int RELEASE_0 = 0x8B;
    public static final int RELEASE_Z = 0xAC;
    public static final int RELEASE_Y = 0x95;
    public static final int RELEASE_X = 0xAD;
    public static final int RELEASE_W = 0x91;
    public static final int RELEASE_V = 0xAF;
    public static final int RELEASE_U = 0x96;
    public static final int RELEASE_T = 0x94;
    public static final int RELEASE_S = 0x9F;
    public static final int RELEASE_R = 0x93;
    public static final int RELEASE_Q = 0x90;
    public static final int RELEASE_P = 0x99;
    public static final int RELEASE_O = 0x98;
    public static final int RELEASE_N = 0xB1;
    public static final int RELEASE_M = 0xB2;
    public static final int RELEASE_L = 0xA6;
    public static final int RELEASE_K = 0xA5;
    public static final int RELEASE_J = 0xA4;
    public static final int RELEASE_I = 0x97;
    public static final int RELEASE_H = 0xA3;
    public static final int RELEASE_G = 0xA2;
    public static final int RELEASE_F = 0xA1;
    public static final int RELEASE_E = 0x92;
    public static final int RELEASE_D = 0xA0;
    public static final int RELEASE_C = 0xAE;
    public static final int RELEASE_B = 0xB0;
    public static final int RELEASE_A = 0x9E;

}
